function [ out ] = filtr( in ,Color)
	Max=1; Min=2;green=2;red=1;blue=3;
out=(...
    in(:,:,1)>=Color(Min,red)&(in(:,:,1)<=Color(Max,red))...
    &in(:,:,2)>=Color(Min,green)&(in(:,:,2)<=Color(Max,green))...
    &in(:,:,3)>=Color(Min,blue)&(in(:,:,3)<=Color(Max,blue))...
    ); 
end

